site_name: MSc Project Guide Book

site_url: https://matthewhiggins2017.github.io/MSc_Project_Guide/
repo_url: https://github.com/MatthewHiggins2017/MSc_Project_Guide

theme:
  name: material
  language: en
  features:
    - content.tooltips
    - navigation.instant
    - navigation.tabs
    - toc.integrate
    - content.tabs.link


markdown_extensions:
  - attr_list
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - pymdownx.keys
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true 

extra_css:
  - stylesheets/extra.css

nav:
  - Home: 
    - index.md